version: "2"
services:
  app:
    build: ./app
    env_file:
      - ./do_we_get_tacos_today/.env
    expose:
      - "8000"
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
